### PR TITLE
Variational Auto Encoder

### PR DESCRIPTION
**Pull request by arpitsomani8**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Slight Changes Required:
outer_units = 32 
inner_units = x_train.shape[1]

Change above code to :
outer_units = x_train.shape[1]
inner_units = round(x_train.shape[1]/2)

reason :
This makes the neural structure generic for any dataset. because the if we set outlayer to 32 it will throw error for any dataset having more then 32 features.

**Comment by arpitsomani8** [comment]
done

**Comment by Thilakraj1998** [comment]
Changes required
you have only specified encoder neuron.
Since this model is type of AutoEncoder it requires decoder neuron unit as well.

just change the argument/parameter of model to:

model = VAE(epochs=10, 
                    contamination=0.05, 
                    encoder_neurons = [outer_units,inner_units],
                    decoder_neurons =[inner_units,outer_units]
) .
This is right initialization for VAE model

**Comment by arpitsomani8** [comment]
> 
> 
> Changes required
> you have only specified encoder neuron.
> Since this model is type of AutoEncoder it requires decoder neuron unit as well.
> 
> just change the argument/parameter of model to:
> 
> model = VAE(epochs=10,
> contamination=0.05,
> encoder_neurons = [outer_units,inner_units],
> decoder_neurons =[inner_units,outer_units]
> ) .
> This is right initialization for VAE model

ok... done...

**Comment by Thilakraj1998** [comment]
Also rerun the file
the model printed has different architecture

**Comment by arpitsomani8** [comment]
> 
> 
> Also rerun the file
> the model printed has different architecture

done

**Pull request merged**
