### PR TITLE
Traffic Sign Recognition

### PR DESCRIPTION
**Pull request by ageerHarikrishna**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Can this be implemented in tensorflow 2.0 and also there are some unwanted linux bash commands please remove them before submitting

**Comment by ageerHarikrishna** [comment]
when I try to change the version I faced some errors so that's why I sued the older version. And I removed the unwanted Linux bash.

**Comment by Thilakraj1998** [comment]
what is the issue getting on tensorflow version upgrade

**Comment by ageerHarikrishna** [comment]
I will try again sir, By evening I will try to do it in tenserflow  version 2

**Pull request closed without merging**
