### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by abhishek-252**
Isomaps

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Can we get description on how the components are selected in ISOMAP

**Comment by abhishek-252** [comment]
Added descriptions

**Comment by Thilakraj1998** [comment]
Is it possible to add a visualization plot. just to showcase manifold generate out of ISOMAP

**Comment by abhishek-252** [comment]
I didn't understand .. can you please elaborate?

**Comment by Thilakraj1998** [comment]
I mean to say, can we implement a scatter plot to visualize the data after transformation using Isomap

**Pull request merged**
