### PR TITLE
Simple Image Classification using ANN

### PR DESCRIPTION
**Pull request by arpitsomani8**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Required Changes:

1. outputlayer/last layer must have number of units equal number of classes in case of multiclass classification or 1 in case binary classification.
2. is this description required: Model Tuning Parameters¶
n_estimators -> Number of Dense layer.
3. output of sample data is not there but code exists

for example:
model.add(Dense(1024, input_shape=(X_train.shape[1],), activation="relu"))   # first hidden layer has 1024 nodes
model.add(Dense(, activation="sigmoid"))

**Comment by arpitsomani8** [comment]
Above changes done, but i am facing error in last three codes.

In Model Accuracy
AttributeError: 'Sequential' object has no attribute 'score'

In Confusion Matrix
ValueError: plot_confusion_matrix only supports classifiers

In Classification Report
ValueError: Classification metrics can't handle a mix of binary and continuous-multioutput targets

**Comment by arpitsomani8** [comment]
How to solve them ?

**Comment by arpitsomani8** [comment]
This data is used.

https://drive.google.com/open?id=1dbcWabr3Xrr4JvuG0VxTiweGzHn-YYvW

**Comment by Thilakraj1998** [comment]
To Debug this issue.
first you must understand how te prediction looks like
1. Tensorflow library doesnt have score function for testing accuracy : utilize model.evaluate(test)
2. for confusion matrix use confusion_matrix(Y_test,y_pred)
3. for classification report also you have first understand and manipulate the predicted output

**Comment by Thilakraj1998** [comment]
For instance your resulting neural network has wrong architecture in terms of output layer
Reason : number of neurons in last layer should be either equal to number of classes in target  or 1 in case of binary classification

at same time activation function influence result outputs. for binary problem it preferred to use sigmoid (returns either 1 or 0)
while for multiclass classification problem softmax(returns probability of each available classes) activation function is preferred

the reason why the classification report throws error is due to mismatch in y_test and predicted data
your y_test is binary in nature while your y_pred is not.

**Comment by arpitsomani8** [comment]
i did not understand the exact issue with output layer.
What to change exactly ? and again how ?

**Comment by arpitsomani8** [comment]
https://colab.research.google.com/drive/1gnATlBplxD2QYtXN5xZ9CTYCF9fQbBeq?usp=sharing

**Pull request merged**
